name: fss_variants_contrast
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_seed_scheme: ^3.0.0
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2762.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    # for google fonts make sure to add that folder
    - assets/images/
    - assets/google_fonts/
